site_name: KFC Procedure
site_url: https://ougi3ay.github.io/kfc-procedure/
repo_url: https://github.com/Ougi3ay/kfc-procedure

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src