"""
Types and data structures used across the library for representing.
"""
from __future__ import annotations

import numpy as np
from dataclasses import dataclass


@dataclass(slots=True)
class SplitIndices:
    """
    Index sets defining a train/evaluation partition.

    This container stores the row indices corresponding to the
    training subset and evaluation subset generated by a data
    splitting strategy.

    Parameters
    ----------
    train_idx : ndarray of shape (n_train,)
        Indices assigned to the training subset.

    eval_idx : ndarray of shape (n_eval,)
        Indices assigned to the evaluation subset.

    fold_id : int or None, default=None
        Optional fold identifier when the split originates from
        a cross-validation procedure.

    Notes
    -----
    Instances of this class are produced by data splitters and
    consumed by training workflows throughout the library.
    """

    train_idx: np.ndarray
    eval_idx: np.ndarray
    fold_id: int | None = None


@dataclass(slots=True)
class TrainingContext:
    """
    Container holding the datasets required during model training.

    The context encapsulates the feature matrices, target vectors,
    and prediction mode information used by ensemble aggregation
    procedures.

    Parameters
    ----------
    X_k : ndarray of shape (n_samples_k, n_features) or None
        Feature matrix used for estimator fitting. May be ``None``
        when precomputed predictions are supplied directly.

    y_k : ndarray of shape (n_samples_k,) or None
        Target values associated with ``X_k``.

    X_l : ndarray of shape (n_samples_l, n_features)
        Aggregation or calibration feature matrix.

    y_l : ndarray of shape (n_samples_l,)
        Aggregation or calibration target values.

    as_predictions : bool
        Indicates whether the provided inputs represent raw
        features or precomputed estimator predictions.

    Notes
    -----
    This object is typically created by data preparation utilities
    before estimator training and aggregation stages.
    """

    X_k: np.ndarray | None
    y_k: np.ndarray | None

    X_l: np.ndarray
    y_l: np.ndarray

    as_predictions: bool
