"""
F-step (local model fitting stage) in the KFC pipeline.

This module implements the F-step of the KFCProcedure framework, where
local predictive models are trained within each cluster induced by
the K-step divergence-specific clustering.

Overview
--------
Given:

    * X ∈ R^{n × d} input features
    * y ∈ R^n targets
    * cluster assignments from K-step:

        C_d = {c_1, c_2, ..., c_K}

the F-step fits independent local models:

    f_{d,k} : X_{c_k} → y_{c_k}

for each divergence d and each cluster k.

This results in a collection of specialized models:

    M = {M_{d,k}}

which capture local structure within divergence-induced partitions.

Key Idea
--------
Instead of fitting a single global model, the F-step learns a set of
cluster-specific predictors, enabling:

* local adaptivity
* reduced model bias
* divergence-aware specialization

Model structure
---------------
For each divergence:

    for each cluster k:
        train local_model on (X_k, y_k)

Prediction aggregates all local models across divergences.

Outputs
-------
models_
    Nested dictionary of trained models:

        models_[divergence][cluster_id]

Prediction shape
----------------
Returns a matrix of shape:

    (n_samples, n_divergences)

where each column corresponds to predictions under one divergence
partitioning.

Notes
-----
* Each divergence induces a different partition → independent model sets
* Cluster-specific models are trained independently
* Missing clusters are safely skipped
"""

from __future__ import annotations

from abc import ABC
from typing import Dict, Optional, Union

import numpy as np
from sklearn.base import BaseEstimator
from sklearn.utils.validation import check_is_fitted

from kfc_procedure.core.ml.base import (
    BaseLocalModel,
    LocalModelFactory,
)
class FStep(ABC, BaseEstimator):
    """
    Local model fitting stage of the KFC pipeline.

    The F-step trains separate predictive models inside each cluster
    generated by the K-step clustering stage. Each divergence produces
    its own clustering structure, and a dedicated set of local models
    is trained per structure.

    Parameters
    ----------
    local_model : str or BaseLocalModel
        Base model used for local learning. Can be:
        - string identifier resolved via LocalModelFactory
        - pre-instantiated model object

    local_model_params : dict, default={}
        Parameters passed to the local model constructor.

    task : str, default="regression"
        Learning task type. Used for factory validation.

    random_state : int or None, default=None
        Random seed passed to stochastic models.

    Attributes
    ----------
    models_ : dict
        Nested dictionary storing trained local models:

            models_[divergence_name][cluster_id]

    Methods
    -------
    fit(X, y, clusters)
        Train local models for each cluster and divergence.

    predict(X, clusters)
        Predict using cluster-specific models for each divergence.

    Notes
    -----
    Prediction is performed per divergence:

        * Each divergence has its own clustering assignment
        * Each cluster has its own trained model
        * Outputs are concatenated across divergences

    This design enables divergence-aware local specialization,
    improving flexibility compared to global models.
    """
    def __init__(
        self,
        local_model: Union[str, BaseLocalModel],
        local_model_params: Optional[Dict] = None,
        task: str = "regression",
        random_state: Optional[int] = None,
    ):
        self.local_model = local_model
        self.local_model_params = local_model_params or {}
        self.task = task
        self.random_state = random_state

    def fit(self, X, y, clusters: Dict[str, np.ndarray]):
        X = np.asarray(X)
        y = np.asarray(y)

        self.models_ = {}

        for div_name, cluster_ids in clusters.items():
            self.models_[div_name] = {}
            for k in np.unique(cluster_ids):
                idx = cluster_ids == k
                if np.sum(idx) == 0:
                    continue
                Xc, yc = X[idx], y[idx]
                model = self._resolve()
                model.fit(Xc, yc)

                self.models_[div_name][f"m{k}"] = {
                    "divergence" : div_name,
                    "cluster": int(k),
                    "model": model,
                }
        
        return self
    
    def predict(self, X, clusters: Dict[str, np.ndarray]):
        check_is_fitted(self, "models_")
        X = np.asarray(X)

        outputs = []
        for div_name, models in self.models_.items():
            pred = np.full(X.shape[0], np.nan)
            cluster_ids = clusters[div_name]

            for _, meta in models.items():
                k = meta["cluster"]
                model = meta["model"]

                idx = cluster_ids == k

                if np.any(idx):
                    pred[idx] = model.predict(X[idx])
            outputs.append(pred.reshape(-1, 1))

        return np.column_stack(outputs)


    
    def _resolve(self) -> BaseLocalModel:
        """
        Build model from factory or reuse instance.
        """

        if not isinstance(self.local_model, str):
            return self.local_model

        name = self.local_model.lower()

        if not LocalModelFactory.contains(name):
            raise ValueError(
                f"Invalid local model: {name}. "
                f"Available: {LocalModelFactory.available()}"
            )

        if not LocalModelFactory.supports(name, self.task):
            raise ValueError(
                f"{name} not supported for task={self.task}. "
                f"Available: {LocalModelFactory.available_by_category(self.task)}"
            )
        
        params = dict(self.local_model_params)
        
        if "random_state" not in params:
            params["random_state"] = self.random_state

        return LocalModelFactory.create(
            name,
            **params,
        )